### ISSUE TITLE
Call to FilePond Instance AddFiles() can't find js addFiles function

### ISSUE THREAD

**Issue by gthoma2** [soenneker/soenneker.blazor.filepond#858]
Blazor server project using .Net 8

In my custom file upload component I'm trying to load in a list of files to the FilePond instance like so:
```C#
protected override async Task OnAfterRenderAsync(bool firstRender)
{
    if (firstRender)
    {
        try
        {
            if (!FileList.IsNullOrEmpty())
            {
                var fileUris = FileList.Select(fileList => fileList.Uri).ToList();

                await _filePond!.AddFiles(fileUris);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "An error occurred while rendering filepond.");
        }
    }
}
```

Can confirm the _filePond instance is not null and the fileUris are properly populated. When it enters the _filePond!.AddFiles(fileUris), I get this error thrown: 

```
Microsoft.JSInterop.JSException: 'Cannot read properties of undefined (reading 'addFiles')
TypeError: Cannot read properties of undefined (reading 'addFiles')
    at Object.addFiles (https://localhost:7026/_content/Soenneker.Blazor.FilePond/filepondinterop.js:39:18)
    at https://localhost:7026/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7026/_framework/blazor.web.js:1:3201)
    at gn._invokeClientMethod (https://localhost:7026/_framework/blazor.web.js:1:62841)
    at gn._processIncomingData (https://localhost:7026/_framework/blazor.web.js:1:60316)
    at connection.onreceive (https://localhost:7026/_framework/blazor.web.js:1:53957)
    at i.onmessage (https://localhost:7026/_framework/blazor.web.js:1:82102)'
```

I've based my using FilePond component off of the ReadMe instructions, so I can confirm that all imports 
 and initializations are correct.
1. filepond.min.js is being found
2. filepondinterop.js is being found
3. In program.cs builder.Services.AddFilePond(); added before app = builder.Build();
4. @using Microsoft.JSInterop &  @using Soenneker.Blazor.FilePond added to imports
5. FileUpload component defines a FilePond property and assigns it to the FilePond markup's @ref parameter.

I can see in the browser inspector that the interop js file exists, and the addFiles function is defined & being exported:
![image](https://github.com/soenneker/soenneker.blazor.filepond/assets/2625843/3177c264-ecef-4093-8c8f-9484e1aa4f67)

![image](https://github.com/soenneker/soenneker.blazor.filepond/assets/2625843/e9c395ba-6e9b-4c53-8de6-639d3bb06e08)

So I'm not sure what's going on where it says that it can't find the addFiles function in the js file.

**Comment by soenneker** [comment]
@gthoma2 It looks like you may be a few versions behind, can you update your NuGet package?

It's not complaining about `addFiles` function being missing, it's complaining that `pond` is undefined after it looks it up from the array.

This is unusual because the component should be created before OnAfterRenderAsync, so I get a feeling something is intercepting it's creation.

> FileUpload component defines a FilePond property and assigns it to the FilePond markup's @ref parameter.

What do you mean by this? Can you show me the Razor?

Have you checked the demos? Are you doing anything differently than those?

**Comment by gthoma2** [comment]
Here's what I meant by the @ref comment: 
**razor.cs of custom file upload component:**
![image](https://github.com/soenneker/soenneker.blazor.filepond/assets/2625843/a1e7bf24-e26d-4cac-b420-e61f64beceba)

**razor of custom file upload component:**
![image](https://github.com/soenneker/soenneker.blazor.filepond/assets/2625843/1c1e7bb8-e227-47f7-bd76-5921651bf01e)

I was just trying to highlight that the _filePond property in my custom class is being populated in the Dom, so at the AfterRenderAsync() point in time, it should exist. Through breakpoints set there, this is what I'm seeing... there is an object there:
![image](https://github.com/soenneker/soenneker.blazor.filepond/assets/2625843/b43b8f82-2cb7-445b-a0ec-e4dd46e0273e)

I updated the nuget package, but am still seeing this error: 
```
Exception thrown: 'Microsoft.JSInterop.JSException' in System.Private.CoreLib.dll
[10:37:20 ERR] An error occurred while rendering filepond.
Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'addFiles')
TypeError: Cannot read properties of undefined (reading 'addFiles')
    at Object.addFiles (https://localhost:7026/_content/Soenneker.Blazor.FilePond/filepondinterop.js:63:18)
    at https://localhost:7026/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:7026/_framework/blazor.web.js:1:3201)
    at gn._invokeClientMethod (https://localhost:7026/_framework/blazor.web.js:1:62841)
    at gn._processIncomingData (https://localhost:7026/_framework/blazor.web.js:1:60316)
    at connection.onreceive (https://localhost:7026/_framework/blazor.web.js:1:53957)
    at i.onmessage (https://localhost:7026/_framework/blazor.web.js:1:82102)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, CancellationToken cancellationToken, Object[] args)
   at KeyFlow2.Forms.Common.Components.FileUploadJS.OnAfterRenderAsync(Boolean firstRender) in C:\Users\gthomas-ramos\source\repos\KEYENCEKASystem\KeyFlow2\KeyFlow2\Forms\Common\Components\FileUploadJS.razor.cs:line 79
```

I will double check the demo project and compare to mine. I haven't worked with JSINterop **too much** before, so I'm not totally confident where to start looking.

Thanks for any assistance.

**Comment by soenneker** [comment]
What I'd do is set a breakpoint within the create function in JS. Pay special attention to what the elementId is. 

Then set another breakpoint within the addFiles JS function, and make sure the elementId is the same, and that the ponds array is populated with that id.

Another troubleshooting procedure I'd do is call addFiles in a different method, on button click or something.

**Comment by gthoma2** [comment]
Thank you for your guidance. I will try this out and let you know.

**Comment by soenneker** [comment]
@gthoma2 please give the latest version a try and let me know if this is fixed, thank you

**Comment by soenneker** [comment]
Closing, feel free to reopen if you continue to run into this after updating.
