### ISSUE TITLE
CS1061: 'FilePond' does not contain a definition for 'EnablePlugins'

### ISSUE THREAD

**Issue by DoomerDGR8** [soenneker/soenneker.blazor.filepond#889]
I had a template using some older version of FilePond but since I upgraded to v2.1.900, I startyed getting this error:

CS1061: 'FilePond' does not contain a definition for 'EnablePlugins' and no accessible extension method 'EnablePlugins' accepting a first argument of type 'FilePond' could be found (are you missing a using directive or an assembly reference?)

![image](https://github.com/soenneker/soenneker.blazor.filepond/assets/825078/b86f85fe-f2f5-471e-bf04-a6c78650362b)

**Comment by soenneker** [comment]
Hi @DoomerDGR8, unfortunately I needed to change the API some. The new way is to register your plugins in `FilePondOptions` `EnabledPlugins` property. An example is in the readme.

I'm continuing to work on the plugin registration dynamic script and style loading, stand by..

**Comment by soenneker** [comment]
@DoomerDGR8 I've added the majority of the plugins to be autoinjected, going to close. If you continue to run into this after updating, please feel free to reopen. Thanks
